### ISSUE TITLE
was working the other day 

### ISSUE THREAD

**Issue by brianzz462** [ryanontheinside/ComfyUI_RyanOnTheInside#18]
Traceback (most recent call last):
  File "F:\AI_install\image generation\ComfyUI_windows_portable\ComfyUI\nodes.py", line 2012, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\AI_install\image generation\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_RyanOnTheInside\__init__.py", line 43, in <module>
    from .nodes.masks.temporal_masks import (
  File "F:\AI_install\image generation\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_RyanOnTheInside\nodes\masks\temporal_masks.py", line 1, in <module>
    from .mask_base import TemporalMaskBase
  File "F:\AI_install\image generation\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_RyanOnTheInside\nodes\masks\mask_base.py", line 5, in <module>
    from .mask_utils import (
  File "F:\AI_install\image generation\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_RyanOnTheInside\nodes\masks\mask_utils.py", line 9, in <module>
    from skimage import draw
ModuleNotFoundError: No module named 'skimage'

Cannot import F:\AI_install\image generation\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_RyanOnTheInside module for custom nodes: No module named 'skimage'

**Comment by brayevalerien** [comment]
`pip install scikit-image`
in your venv
