### ISSUE TITLE
Getting ModuleNotFound error

### ISSUE THREAD

**Issue by Nick-A2B** [ryanontheinside/ComfyUI_RyanOnTheInside#24]
Hello,
I added your node and run pip install -r requirements.txt.
Saw scikit-image-0.24.0 in a list of installed modules, however when starting ComfyUI, I am getting this error:

Traceback (most recent call last):
  File "D:\Work\AI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 2027, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "D:\Work\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_RyanOnTheInside\__init__.py", line 45, in <module>
    from .nodes.masks.temporal_masks import (
  File "D:\Work\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_RyanOnTheInside\nodes\masks\temporal_masks.py", line 1, in <module>
    from .mask_base import TemporalMaskBase
  File "D:\Work\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_RyanOnTheInside\nodes\masks\mask_base.py", line 5, in <module>
    from .mask_utils import (
  File "D:\Work\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_RyanOnTheInside\nodes\masks\mask_utils.py", line 9, in <module>
    from skimage import draw
ModuleNotFoundError: No module named 'skimage'

**Comment by Nick-A2B** [comment]
Fixed by installing pip packages inside of Manager
